chore: grafana disable by default
prevents:

```
module.devops_stack_green.module.argocd_bootstrap.null_resource.this: Refreshing state... [id=6202176565795625097]

Error: Unsupported attribute

  on .terraform/modules/devops_stack_green.prometheus-stack/locals.tf line 89, in locals:
  89:             client_id                = "${replace(local.grafana.oidc.client_id, "\"", "\\\"")}"
    ├────────────────
    │ local.grafana is object with 5 attributes

This object does not have an attribute named "oidc".

Error: Unsupported attribute

  on .terraform/modules/devops_stack_green.prometheus-stack/locals.tf line 90, in locals:
  90:             client_secret [***obfuscated string***]
    ├────────────────
    │ local.grafana is object with 5 attributes

This object does not have an attribute named "oidc".

Error: Unsupported attribute

  on .terraform/modules/devops_stack_green.prometheus-stack/locals.tf line 92, in locals:
  92:             auth_url                 = "${replace(local.grafana.oidc.oauth_url, "\"", "\\\"")}"
    ├────────────────
    │ local.grafana is object with 5 attributes

This object does not have an attribute named "oidc".

Error: Unsupported attribute

  on .terraform/modules/devops_stack_green.prometheus-stack/locals.tf line 93, in locals:
  93:             token_url                = "${replace(local.grafana.oidc.token_url, "\"", "\\\"")}"
    ├────────────────
    │ local.grafana is object with 5 attributes

This object does not have an attribute named "oidc".

Error: Unsupported attribute

  on .terraform/modules/devops_stack_green.prometheus-stack/locals.tf line 94, in locals:
  94:             api_url                  = "${replace(local.grafana.oidc.api_url, "\"", "\\\"")}"
    ├────────────────
    │ local.grafana is object with 5 attributes

This object does not have an attribute named "oidc".
```